version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/arm64 # modify this if you are not on an M1/M2 Mac
    ports:
      - "3001:3001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
      - backend_temp:/app/transcript_extraction/temporary_files
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/arm64 # modify this if you are not on an M1/M2 Mac
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    restart: unless-stopped

volumes:
  backend_temp: